# Generated by Django 4.2.3 on 2023-10-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autoDriveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('description', models.TextField(max_length=400, verbose_name='描述')),
                ('input_video', models.FileField(upload_to='', verbose_name='视频')),
                ('output_video', models.FileField(upload_to='', verbose_name='视频')),
            ],
            options={
                'verbose_name': '模型',
                'verbose_name_plural': '模型',
            },
        ),
    ]
